name: Genshin Auto Login

on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    name: Send login request
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run:  |
          curl --location --request POST 'https://api.mbaharip.me/v1/schedule/genshin' \
          --header 'x-api-key: ${{ secrets.API_KEY }}' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'accId=${{ secrets.ACC_ID }}' \
          --data-urlencode 'uuid=${{ secrets.UUID }}' \
          --data-urlencode 'lToken=${{ secrets.LTOKEN }}' \
          --data-urlencode 'cookie=${{ secrets.COOKIE }}' \
          --data-urlencode 'loginTicket=${{ secrets.LOGIN_TICKET }}' 
